### ISSUE TITLE
Django 환경세팅

### ISSUE THREAD

**Issue by soonyoung-hwang** [soonyoung-hwang/Blog-Django-Bootstrap#1]
## Description

Django 초기 환경세팅을 진행합니다.

## Todo

- [x] Django 프로젝트 설정
- [x] 초기 세팅 1 (migration, ...)
- [x] 초기 세팅 2 (관리자페이지 만들기)

## Reference

- p129-136.
