### ISSUE TITLE
Landing 페이지, About me 페이지 만들기

### ISSUE THREAD

**Issue by soonyoung-hwang** [soonyoung-hwang/Blog-Django-Bootstrap#12]
## Description

Landing Page와 About me 페이지를 만듭니다.

## Todo

- [x] Single Page App을 만듭니다.
- [x] Landing page : url 설정, view 설정, template 만들기
- [x] About me : url 설정, view 설정, template 만들기

## Reference

- p182-186.
