### ISSUE TITLE
Post 목록, Post 상세 모듈화하기

### ISSUE THREAD

**Issue by soonyoung-hwang** [soonyoung-hwang/Blog-Django-Bootstrap#30]
## Description

post list, post detail 페이지를 모듈화합니다.
메인 영역을 제외한 부분을 Template으로 만들어서 디자인적으로 일관성을 유지하게 합니다.

## Todo

- [x] 공통부분 base.html으로 만들기
- [x] post list를 모듈화
- [x] post detail을 모듈화

## Reference

- p264-275.
