### ISSUE TITLE
내비게이션바, 푸터도 모듈화 하고 기능 구현하기

### ISSUE THREAD

**Issue by soonyoung-hwang** [soonyoung-hwang/Blog-Django-Bootstrap#35]
## Description

현재의 내비게이션바는 href 기능이 구현되어있지 않습니다.
내비게이션바의 href 를 구현하고, 내비게이션바와 푸터를 모듈화 합니다.

## Todo

- [x] Test Code 모듈화
- [x] Test Code에 내비게이션 href 테스트 추가
- [x] 내비게이션, 푸터 html 모듈화 및 href 기능구현

## Reference

- p276-285.
