### ISSUE TITLE
Author 추가하기

### ISSUE THREAD

**Issue by soonyoung-hwang** [soonyoung-hwang/Blog-Django-Bootstrap#37]
## Description

Author를 추가하고, Post 와 연결해줍니다.

## Todo

- [x] Author 추가 및 Post와 1대 다 연동
- [x] User 미 설정시, 기본 User로 pk=1의 User로 설정
- [x] Post에 Author 정보 보이도록 변경
- [x] Author 삭제 시 연동된 포스트 삭제되게 구현

## Reference

- p287-305.
- User 생성시, 새로운 Class를 내가 만드는 것 보다, django User 받아 쓰는 것이 훨씬 효율적이다.
  ``` from django.contrib.auth.models import User ```
